### ISSUE TITLE
Latest Nitter image seems broken (regression)

### ISSUE THREAD

**Issue by artemislena** [unixfox/periodic-build-with-github-actions#5]
fc17 We're getting this error:
`May 19 18:15:36 rp64-alu nitter[478876]: /entrypoint.sh: exec: line 53: su-exec: not found`

**Comment by unixfox** [comment]
Fix deployed, waiting for the build on https://github.com/unixfox/periodic-build-with-github-actions/actions/runs/2359468147

Meanwhile you can use an older Docker image tag from the ones available here: https://quay.io/repository/unixfox/nitter?tab=tags&tag=latest

**Comment by artemislena** [comment]
That build finished… but we're still getting the same error… Latest one working is `build-20220513`…

**Comment by unixfox** [comment]
Are you sure you used the very latest build? It works fine for me on my side.
Try cleaning the image cache and pull again the image.

**Comment by artemislena** [comment]
Oh, thanks… guess it had some old image cached for `latest`…
